<?php

/*
 * Implements hook_install().
 * Make this module heavy as the JS needs to be added last.
 */
function intellitxt_install() {
  db_update('system')
    ->fields(array('weight' => 99))
    ->condition('name', 'intellitxt', '=')
    ->execute();
}

/*
 * Implements hook_uninstall().
 *  Clean up. Remove vars
 */
function intellitxt_uninstall() {
  variable_del('intellitxt_sections');
  variable_del('intellitxt_domain');
  variable_del('intellitxt_configured');
}